services:
  - type: web
    name: wedding-invitation
    env: java
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/KotaRiho_Wedding-Invitation-0.0.1-SNAPSHOT.jar"
    repo: https://github.com/rihowatanabeTMT/wedding-invitation
    branch: main